#!/bin/bash
# strta/bootstrap: Resolve all dependencies that the application requires to
#                   run.
set -euo pipefail
shopt -s inherit_errexit
PROJECT_ROOT=$(git rev-parse --show-toplevel)

echo "==> Installing npm dependencies…"
npm ci

echo "==> Bootstrapping is now done!"
